#pragma once
#include <QApplication>
#include <QWidget>
#include <QMainWindow>
#include <QMessageBox>
#include <QMetaObject>
#include <QDragEnterEvent>
#include <QMimeData>
#include <QFileDialog>
#include <QRegularExpression>
#include <QRegularExpressionValidator>
