#pragma once
#include <QApplication>
#include <QCoreApplication>
#include <QThread>
#include <QWidget>
#include <QMainWindow>
#include <QMessageBox>
#include <QMetaObject>
#include <QDragEnterEvent>
#include <QMimeData>
#include <QFileDialog>
#include <QRegularExpression>
#include <QRegularExpressionValidator>
#include <QClipboard>
#include <QTimer>
